### ISSUE TITLE
Google Secret Manager: unable get value from secret manager with Spring Boot

### ISSUE THREAD

**Issue by RamonaMaria** [GoogleCloudPlatform/spring-cloud-gcp#1229]
I followed the [documentation]( https://docs.spring.io/spring-cloud-gcp/docs/current/reference/html/secretmanager.html#_secret_manager_property_source ) and the bootstrap.yml file looks like this:

```
spring:
   clouds:
     gcp:
       secret manager:
         enabled: true
         secret-name-prefix: "sm://"
         project-id: my-project-id
   datasource:
     username: "${sm://datasource-username}"
     password: "${sm://datasource-password}"
```
 and the application.yml file looks like this:
```
spring:
   clouds:
     gcp:
       projectId: my-project-id
       SQL:
         instance-connection-name: "my-instance"
         databaseName: testDatabase
```
I followed the documentation https://docs.spring.io/spring-cloud-gcp/docs/current/reference/html/secretmanager.html#_secret_manager_property_source and the bootstrap.yml file looks like this:

spring:
   clouds:
     gcp:
       secret manager:
         enabled: true
         secret-name-prefix: "sm://"
         project-id: my-project-id
   data source:
     username: "${sm://datasource-username}"
     password: test
and the application.yml file looks like this:

spring:
   clouds:
     gcp:
       projectId: my-project-id
       SQL:
         instance-connection-name: "my-instance"
         databaseName: testDatabase
and I get this error:

```
Property: spring.datasource.username\n Value: ${sm://datasource-username}\n Origin: class path resource [bootstrap.yml] - 9:15\n
Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.google.protobuf.ByteString$LiteralByteString] to type [java.lang.String]\n\nAction:\n\nUpdate your application's configuration\n"}
```

I also saw the solution implemented #955  and my code looks like this:

```
@SpringBootApplication
class Application

fun main(args: Array<String>) {
	(DefaultConversionService.getSharedInstance() as DefaultConversionService).addConverter(CustomConverter())
	SpringApplication.run(Application::class.java, *args)
}
```

```
@Component
class CustomConverter : GenericConverter {
    override fun getConvertibleTypes(): Set<ConvertiblePair>? {
        return Collections.singleton(ConvertiblePair(ByteString::class.java, String::class.java))
    }

    override fun convert(
        source: Any?, sourceType: TypeDescriptor,
        targetType: TypeDescriptor
    ): Any? {
        var source = source
        if (sourceType.type == String::class.java) {
            return source
        }
        try {
            source = (source as ByteString?)!!.toString("UTF-8")
        } catch (e: UnsupportedEncodingException) {
            e.printStackTrace()
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return source
    }
}
```
but the error still persists. :( 

what am i doing wrong?

Many thanks!
