### ISSUE TITLE
Config Map Configuration Support Gone ??

### ISSUE THREAD

**Issue by rking-bennie** [GoogleCloudPlatform/spring-cloud-gcp#1365]
**Describe the bug**
In older documentation it was shown which dependency was needed to connect to GKE Config Maps. In all the latest documentation, it lists all other GKE resources except config maps. Using the latest version, my application no longer looks for config map in GKE environment. Can this be explained. Document here does not: https://googlecloudplatform.github.io/spring-cloud-gcp/3.4.0/reference/html/index.html

Spring application has this in bootstrap as older versions would have necessitated

```
spring:
    cloud:
      kubernetes:
        config:
          name: ${spring.application.name}
          namespace: ##INSERT NAMESPACE HERE
          sources:
            - name: ${spring.application.name}
```

**Sample**
Any application with above configuration in bootstrap.yml that needs to connect to config map in GKE environment.
