### ISSUE TITLE
Why cloud sql do not configure in boostrap mode?

### ISSUE THREAD

**Issue by accnetodevel** [GoogleCloudPlatform/spring-cloud-gcp#1464]
**Describe the bug**

I'm trying to use cloud sql in a spring cloud config project in boostrap mode with jdbc profile.
However, when configuring the boostrap mode, it fails to inject the connection to the database, failing the startup of my application.

**Sample**

see `boostrap.yml`

```yml
spring:
  profiles:
    active: jdbc
  application:
    name: config-server
  cloud:
    config:
      name: config-server
      label: master
      enabled: true
      server:
        bootstrap: true
        jdbc:
          order: 1
          sql: select key, value from properties where application in (?, 'general') and profile=? and label=?
    gcp:
      project-id: ${my-project-id}
      sql:
        database-name: config
        instance-connection-name: ${spring.cloud.gcp.project-id}:us-central1:config-server-dbs

```

**Error** 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class
```

if i configure then manually the datasource it works:

```yml
spring:
  profiles:
    active: jdbc
  application:
    name: config-server
  cloud:
    config:
      name: config-server
      label: master
      enabled: true
      server:
        bootstrap: true
        jdbc:
          order: 1
          sql: select key, value from properties where application in (?, 'general') and profile=? and label=?
    gcp:
      project-id: vli-integrarodo-dev
      sql:
        database-name: config
        instance-connection-name: ${spring.cloud.gcp.project-id}:us-central1:config-server-dbs
  datasource:
    url: jdbc:postgresql://localhost:5432/config
    username: config
    password: mypass
    hikari:
      pool-name: config
      idle-timeout: 120000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime:  300000
    type: com.zaxxer.hikari.HikariDataSource
```

configuring it manually is not an option for me as I don't have a public URL, we use a service account for the database connection.

Any idea to solve this?

I found this code in `CloudSqlEnvironmentPostProcessor`

```java
  public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
        if (!environment.getPropertySources().contains("bootstrap")) {
  
  ....

```

**Comment by accnetodevel** [comment]
Hi @JoeWang1127, 

I need why config-server's boostrap mode makes it load the settings for itself, if I don't do that it can't read the properties.

I got a workaround: 
```yml
  gcp:
      project-id: ${my-project-id}
      sql:
        enabled: false # i need disable autoconfiguration 
        database-name: config
        instance-connection-name: ${spring.cloud.gcp.project-id}:us-central1:my-dbs
  datasource: # and a need configure manually a database connection
    url: jdbc:postgresql://google/config?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${spring.cloud.gcp.project-id}:us-central1:my-dbs
    username: config
    hikari:
      pool-name: config
      idle-timeout: 120000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime:  300000
    type: com.zaxxer.hikari.HikariDataSource
```
But I really think this solution is ugly :/

**Comment by accnetodevel** [comment]
Okay, I've tried pulling out of the boostrap phase but it never invokes:
```yml
jdbc:
    order: 1
    sql: select key, value from properties where application in (?, 'general') and profile=? and label=?
```
he even gets the connection using the abstraction of your lib, but he can't read the properties :/

In this new scenario it might be more appropriate to see this issue in the config-server repository

If you agree, you can close this issue.
Thank you for your support.
