### ISSUE TITLE
Can't get Spring Cloud Secret Manger 5.x to work in GKE/Google Cloud

### ISSUE THREAD

**Issue by johanhaleby** [GoogleCloudPlatform/spring-cloud-gcp#2513]
When using 3.2.1 of `spring-cloud-gcp-starter-secretmanager`, the secret manager secrets defined in Google Cloud Secret Manager were successfully applied to our application. But after upgrading to 5.0.0, they won't be resolved. For example, our MongoDB connection string that we store in Google Cloud Secret Manager was read and applied as expected in version 3.2.1. 

However, after upgrading to version 5.0.0, it fails:

```
[my-service-5c4db7447b-sbrgj] Caused by: java.lang.IllegalArgumentException: The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://
[my-service-5c4db7447b-sbrgj] 	at com.mongodb.ConnectionString.<init>(ConnectionString.java:340) ~[mongodb-driver-core-4.11.1.jar!/:na]
[my-service-5c4db7447b-sbrgj] 	at com.mongodb.ConnectionString.<init>(ConnectionString.java:321) ~[mongodb-driver-core-4.11.1.jar!/:na]
[my-service-5c4db7447b-sbrgj] 	at org.springframework.boot.autoconfigure.mongo.PropertiesMongoConnectionDetails.getConnectionString(PropertiesMongoConnectionDetails.java:47) ~[spring-boot-autoconfigure-3.2.1.jar!/:3.2.1]
[my-service-5c4db7447b-sbrgj] 	at org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSettingsConfiguration.standardMongoSettingsCustomizer(MongoAutoConfiguration.java:74) ~[spring-boot-autoconfigure-3.2.1.jar!/:3.2.1]
[my-service-5c4db7447b-sbrgj] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
[my-service-5c4db7447b-sbrgj] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
[my-service-5c4db7447b-sbrgj] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.2.jar!/:6.1.2]
[my-service-5c4db7447b-sbrgj] 	... 112 common frames omitted
```

We have not changed the value of the MongoDB URI in Google Cloud Secret Manager, and it works again if downgrading to version 3.2.1.

Here's our `application.yaml`:

```yaml
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: my-service
  data:
    mongodb:
      uri: "${sm://my_service__mongodb_uri}"
  rabbitmq:
    addresses: "${sm://common__rabbitmq_uri}"
  cloud:
    config:
      import: sm://
    gcp:
      trace:
        enabled: true
      project-id: my-gcp-project-id
```

What am I missing?
