### ISSUE TITLE
Add documentation for using Cloud Memorystore with TLS and/or authentication

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#2735]
The current [Spring Cloud GCP Memorystore for Redis documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html#cloud-memorystore-for-redis) says:

> All you have to do is create a Cloud Memorystore instance and use its IP address in application.properties file as `spring.redis.host` property value.

`spring.redis.host` has been deprecated and replaced with `spring.data.redis.host`, but I also found that only configuring the IP address is not enough. My Cloud Memorystore instances use port `6378`, while Spring Boot's `RedisProperties` class defaults to port `6379`, so I also had to set `spring.data.redis.port` to `6378`.

Also, my company requires using TLS, and it took me a while to figure out how to connect to Cloud Memorystore in that scenario.

I ended up with something like this:

```
spring:
  data:
    redis:
      host: 10.0.0.1 # Find actual IP address on https://console.cloud.google.com/memorystore/redis/instances
      port: 6378          # Find port on https://console.cloud.google.com/memorystore/redis/instances
      ssl:
        bundle: cloud-memorystore # See 'spring.ssl.bundle.pem.cloud-memorystore'
  ssl:
    bundle:
      pem:
        cloud-memorystore:
          truststore:
            certificate: file:/cloud-memorystore-server-ca-cert/server-ca.pem # Find the server-ca.pem file via https://console.cloud.google.com/memorystore/redis/instances > Security, and make it available in your application container. Could also be added as a classpath resource of course.
```

On top of that my company also requires authentication. For this `spring.data.redis.password` needed to be set to the auth string that can be found via https://console.cloud.google.com/memorystore/redis/instances. Of course this auth string should not be added to the configuration in plain text, but provided via Secret Manager or a Kubernetes secret or something.

I think it would be good for the Spring Cloud GCP Memorystore for Redis documentation to show how to set both the IP address and port, and also provide some guidance on how to use Cloud Memorystore with TLS and authentication.
