### ISSUE TITLE
SecretManager ignores spring.cloud.gcp.secretmanager.enabled=false where properties file has properties referenced with secret manager prefix

### ISSUE THREAD

**Issue by michaelhalllloyds** [GoogleCloudPlatform/spring-cloud-gcp#3725]
I have been battling with this for a number of days now. We are trying to use spring-cloud-gcp-starter-secretmanager in an application, with the following in application.yml:

```
spring:
  config:
    import: sm@

app:
  config:
    randomProperty: sm@fakeProperty
```

Originally, I was trying to use @TestConfiguration in a @SpringBootTest to override the SecretManagerServiceClient or the SecretManagerTemplate with a mock, but this doesn't seem to work at all as the real implementation is always used.

I gave up on this, and attempted to turn off secretmanager by using the following in application-test.yml and later in bootstrap-test.yml with a Spring Profile called 'test', and this still doesn't disable secretmanager.

```
spring:
  cloud:
    gcp:
      secretmanager:
        enabled: false
      core:
        enabled: false
``` 

A suggestion from a colleague is to put "sm@fakeProperty" inside an env var and refer to it in the properties file as `"${${fakePropertyEnvVar}:defaultValue}"` so that it only attempts to call secret manager if that env var is set (which we just wouldn't do for a test), but it feels like setting `enabled` to `false` should really turn off the functionality completely.

I am also keen to know if it is possible to mock the Template/Client in a @SpringBootTest as this seems the way to get the most control in tests.
