### ISSUE TITLE
sm@ doesn't seem work in Spring Boot 3.5.0

### ISSUE THREAD

**Issue by johanhaleby** [GoogleCloudPlatform/spring-cloud-gcp#3824]
I'm trying to upgrade one of our apps to Spring Boot 3.5.0 and spring-cloud-gcp 6.2.1. 

According to the [docs](https://googlecloudplatform.github.io/spring-cloud-gcp/6.2.1/reference/html/index.html#secret-manager-config-data-resource), you should no longer use the `sm://` config suffix but rather `sm@`. So we've changed from this:

```yaml
spring:
  application:
    name: my-aoo
  config:
    import: sm://
    gcp:
      trace:
        enabled: true
      project-id: my-project
  rabbitmq:
    addresses: "${sm://rabbitmq_uri}"
```

to this:

```yaml
spring:
  application:
    name: my-aoo
  config:
    import: sm@
    gcp:
      trace:
        enabled: true
      project-id: my-project
  rabbitmq:
    addresses: "${sm@rabbitmq_uri}"
```

But now our application doesn't start when we're deploying to K8S:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.rabbitmq' to org.springframework.boot.autoconfigure.amqp.RabbitProperties:

    Property: spring.rabbitmq.addresses
    Value: "${sm@rabbitmq_uri}"
    Origin: URL [file:config/application.yaml] - 29:16
    Reason: java.lang.NumberFormatException: For input string: ""

Action:

Update your application's configuration
```
