### ISSUE TITLE
No environment placeholder in configuration properties

### ISSUE THREAD

**Issue by ElectroLutz** [GoogleCloudPlatform/spring-cloud-gcp#491]
Hey,

I guess that after #131 (edit: I guess it's since 2.0.2) it's not possible to have a configuration like the following anymore:
```
spring.cloud.gcp:
  sql:
    enabled: ${CLOUD_SQL_ENABLED:false}
    database-name: ${CLOUD_SQL_DATABASE:}
    instance-connection-name: ${CLOUD_SQL_INSTANCE:}
    credentials:
      encoded-key: ${CLOUD_SQL_KEY:}
```
The placeholders are not replaced anymore and the values are passed as they are in the application.yml.

How can I archive that they are replaced again? I don't want to use any config management, because until now the environment variables been doing their job.

Cheers
Marko
