### ISSUE TITLE
Not correct priority gcp.sql.credentials - get default application credentials instead of spring.cloud.gcp.sql.credentials.encoded-key

### ISSUE THREAD

**Issue by szopal** [GoogleCloudPlatform/spring-cloud-gcp#796]
Hi, 

I have problem when change group of org.springframework.cloud to com.google.cloud in my spring-cloud-gcp-dependencies. I tried connect with CloudSQL by GCP Service Account passed in spring.cloud.gcp.sql.credentials.encoded-key from Vault (but also try in spring.cloud.gcp.sql.credentials.encoded-key). But instead get my service acount credentials key, Spring Boot app get my default application credentials where I have not acces to CloudSQL. When I changed group again to org.springframework.cloud it work's fine but I read that this functionality was migrate and I should use new version 2.x.x instead of 1.x. 

When I used com.google.cloud I can see that credentials are getting before Vault so I didn't have base64 value but I have String instead with variable name as encoded key.

`<html>
<body>

Spring Cloud GCP is no longer part of the Spring Cloud release train. The new repository location is https://github.com/GoogleCloudPlatform/spring-cloud-gcp. Check out the migration guide to upgrade from version 1.x to 2.0.0.
--

</body>
</html>`

spring-boot-starter-parent version: 2.2.1.RELEASE

bootstrap.yaml
```
spring:
  cloud:
    gcp:
      sql:
        credentials:
          encoded-key: ${GCP_CREDENTIALS_ENCODED_KEY}
```

application.yaml
```
spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: xxxxxx
        database-name: xxxx
  datasource:
    username: xxxx
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 10
      maximumPoolSize: 20
      read-only: true
      schema: xxx
```

I also noticed that spring.cloud.gcp.sql does not have schema properties which can be passed to hikarii.schema. I had to add custom schema setting from properties hikari.schema in my DataSource becauce gcp.sql didn't do it.
